### PR TITLE
Message Board Hibernate Demo by Andrea Boriero <dreab8> and Fabio Ercoli

### PR DESCRIPTION
**Pull request by fax4ever**
We squashed the first user story in two commits.

### CODE REVIEW

**Comment by Sanne** [comment]
@fax4ever looks very nice! could you make some small changes:

- [ ] move the files from _/other/openshift_ to _/openshift_
- [ ] remove the slides (we just keep the demos here)
- [ ] rebase / make sure you pushed all latest

Let me know when it's done, then I'll merge it. I'll also give you write permissions.

**Comment by fax4ever** [comment]
Thanks @Sanne for review. I made the changes.
In the squash of history I've prefered to keep the two original commit: one by me and the other by @dreab8.
is that ok?

**Comment by Sanne** [comment]
ok

**Comment by fax4ever** [comment]
@Sanne I've updated the readme with angular cli prerequirement

**Comment by Sanne** [comment]
merged! thanks all

**Pull request merged**
