### PR TITLE
Demo updates to Hibernate Search 5.8, Elasticsearch 5.6

### PR DESCRIPTION
**Pull request by Sanne**

### CODE REVIEW

**Comment by Sanne** [comment]
> I will fix this dependency issue and merge.

Ok but I generally prefer we state dependency versions explicitly, both to make it clear what's used and to make it easier to override in case of need. But ok that's a very minor opinion.

Thanks for checking & merging!

**Comment by yrodiere** [comment]
> Ok but I generally prefer we state dependency versions explicitly, both to make it clear what's used and to make it easier to override in case of need. But ok that's a very minor opinion.

Seems a bit weird... ? The plugin fetches the elasticsearch distribution artifact explicitly, you know, it's not declared as a dependency: https://github.com/alexcojocaru/elasticsearch-maven-plugin/blob/ac84e0acd6671338b6a23d8695fcf456a09b3492/src/main/java/com/github/alexcojocaru/mojo/elasticsearch/v2/step/ResolveElasticsearchStep.java#L38
(it changed since the version 2.x of the plugin)

Plus, the actual artifact being pulled in is `org.elasticsearch.distribution.zip:elasticsearch:<version>:zip`, so this dependency was actually pulling in an additional, unused artifact.

**Comment by Sanne** [comment]
oh! Ok so we should fix the Hibernate Search poms too? I copied this from there..

**Comment by yrodiere** [comment]
The Hibernate Search poms have two different configurations, one for ES2 (elasticsearch-maven-plugin 2), and one for ES5+ (elasticsearch-maven-plugin 5). I just checked, they seem to be correct.

**Comment by Sanne** [comment]
thanks for checking! Understand it now, I copied it from the wrong profile.

**Pull request merged**
